Cross hyperparameters search
numenta/nupic.research pull request #566
Opened 2021-09-13 15:02 UTC by jeremyforest

config file for generating the cross hyperparameter search (data showed on dendrite meeting at the end of August)

2021-09-14 15:03 UTC, karangrewal requested changes
I have 2 pieces of feedback:

1. I think it would make more sense in the config if you give the optimal parameter configuration instead of code that runs a hyperparameter search. This way, someone else can use your config to run an experiment with optimal choice of hyperparameters. E.g., you would have `num_segments=10` instead of `num_segments=tune.grid_search([5, 10, 50, 100])`. However, if these optimal hyparameter configurations are in some other config and this is just code to do the hyperparameter search, that's fine too.

2. Your Makefile doesn't belong in the repository, please remove that from your commit.

2021-09-27 14:52 UTC, jeremyforest commented
1. yes this is just the code for the search so it should stay as-is
2. makefile allows to run all the scripts generating the figure in one go. 
3. adding more guidlines in the readme file.

2021-09-30 17:40 UTC, jeremyforest commented
@karangrewal I think  this is good to merge. let me know if you have more to add.

2021-09-30 22:48 UTC, karangrewal approved these changes

2021-10-01 11:25 UTC, merged