Add README to dendrites project
numenta/nupic.research pull request #616
Opened 2021-12-02 09:45 UTC by vkakerbeck

Added README from https://github.com/numenta/htmpapers/blob/master/biorxiv/going_beyond_the_point_neuron/README.md to this project folder (without prerequisites section).

2021-12-02 16:05 UTC, subutai requested changes

2021-12-02 16:05 UTC, subutai commented on projects/dendrites/README.md
> +Below are instructions for reproducing all the charts and tables presented in the paper. There might be small differences due to randomness.
Can get rid of this line.

2021-12-02 17:20 UTC, subutai requested changes

2021-12-02 17:20 UTC, subutai commented on projects/dendrites/README.md
> +For the latest pytorch code for using the code in your own projects check the [nupic.research](https://github.com/numenta/nupic.research) and [nupic.torch](https://github.com/numenta/nupic.torch) rep
I think we can get rid of this sentence now.

2021-12-02 17:27 UTC, lscheinkman commented
@vkakerbeck @subutai We should create pull requests from your personal fork  vkakerbeck/nupic.research not branch on the upstream repository numenta/nupic.research

2021-12-02 17:30 UTC, subutai approved these changes

2021-12-02 17:33 UTC, vkakerbeck commented
Oh right, sorry! I will do that next time, totally forgot about it.

2021-12-06 18:15 UTC, karangrewal approved these changes

2021-12-06 21:00 UTC, closed without merging

2021-12-06 21:00 UTC, vkakerbeck commented
New PR from fork here: https://github.com/numenta/nupic.research/pull/619